"""food name column

Revision ID: 3e73b27ae79d
Revises: 80567abddb96
Create Date: 2023-11-15 15:09:46.849236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e73b27ae79d'
down_revision: Union[str, None] = '80567abddb96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foods', 'name')
    # ### end Alembic commands ###
